doctrine:
    dbal:
        driver: 'pdo_sqlite'  # or 'pdo_mysql' if you're using MySQL
        url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: Configure your server version if needed
        # server_version: 'your_server_version_here'
        use_savepoints: true

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation  # Ensure you are using annotations for mapping
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
