version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/html


  web:
    image: nginx:latest
    container_name: symfony_web
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "8080:80"
    depends_on:
      - php

  rabbitmq:
    image: rabbitmq:3-management  # The management version gives you a UI at :15672
    ports:
      - "5672:5672"       # Default port for RabbitMQ
      - "15672:15672"     # Default port for RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq_data: