#index:
#    path: /
#    controller: App\Controller\DefaultController::index


  
api_bitcoin:
    path:       /api/bitcoin
    controller: App\Controller\API\BitcoinAPIController::bitcoin
    methods:    GET|HEAD

api_bitcoin_history:
    path:       /api/bitcoin/history
    controller: App\Controller\API\BitcoinAPIController::getBitcoinValuesHistory
    methods:    GET|HEAD